name: Deploy to Surge.sh

on:
  push:
    branches:
      - main  # Cambia esto si la rama principal se llama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Instalar Surge.sh
      run: npm install -g surge

    - name: Desplegar en Surge.sh
      run: surge --project ./ --domain primerparcial-eliezer.surge.sh
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}